---
title: "Task 3 EDS 221"
author: "Dalila Lara"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 1. Conditional statements & for loops 

# A conditional Statements

Task 1 
```{r}
pm2_5 <- 60
if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if(pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
  } else if (pm2_5 >= 150) {
    print("Health risk present")
  }

```

Task 2 
```{r}
species <- "blue whale"

if(species == "whale") {
  print("You found a whale!")
}
```

Task 3
```{r}
max_airtemp_c <- 25

if( max_airtemp_c > 27) {
  print("Temperature too high")
} else if (max_airtemp_c == 27 & max_airtemp_c <= 27) {
  print("Temperature OK")
}
```

Task 4
```{r}
base_burrito <- 6.50 
main_ingredient <- "veggie"

if(main_ingredient == "veggie") {
  print("A veggie burrito is the cost of a base burrito")
} else if (main_ingredient == "chicken") {
  print("A chicken burrito costs 3.00 more than a base burrito") 
} else if (main_ingredient == "steak") {
  print("A steak burrito costs 3.25 more than a base burrito")
  }

```

# B for loops 
Task 5
```{r}
fish <- c(8, 10, 12, 23)
fish_species <- c("goldfish", "tetras", "guppies", "mollies")

for( i in seq_along(fish)) {
  if(fish_species[i] == "goldfish") {
    count = (fish[i]/sum(fish)) * 100 
  } else if (fish_species[i] == "tetras") {
    count = (fish[i]/sum(fish)) * 100
  } else if (fish_species[i] == "guppies") {
    count = (fish[i]/sum(fish)) * 100
  } else if (fish_species[i] == "mollies") {
    count = (fish[i]/sum(fish)) * 100
  } 
  print(count)
}
```


Task 6
```{r}
# Vector month.name
for(i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))
  }
```

